# Checks if all past commits pass the CI quality gate `cargo xtask ci`,
# excluding moving targets (such as clippy or `cargo audit`).
# This pipeline tries to indicate whether developers may use `git bisect`.

name: Validate entire commit history

on:
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │ ┌───────────── hour (0 - 23)
    #        │ │ ┌───────────── day of the month (1 - 31)
    #        │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │ │ │ │ │
    #        │ │ │ │ │
    #        │ │ │ │ │
    - cron: '0 0 * * MON'

  workflow_dispatch:

jobs:
  check_each_commit:
    name: check each commit
    timeout-minutes: 240
    runs-on: ${{ matrix.system }}

    strategy:
      matrix:
        system: [ ubuntu-latest, windows-latest, macos-latest ]
        branch: [ main ]

    steps:

    # For whatever reason, Git needs user name and email for the rebase
    # on some agents but not on others.
    # Also, sometimes there are linter errors due to changed line endings.
    - name: Configure Git
      run: |
        git config --global user.email "runner@github.com"
        git config --global user.name "GitHub, Runner"
        git config --global core.autocrlf false

    - uses: actions/checkout@v4
      with:
        ref: ${{ matrix.branch }}
        fetch-depth: 0

    # Rust 1.80 removed support of the `tarpaulin_include` attribute,
    # so commit `57cc064` and before only work with Rust 1.79.
    - name: Install 1.79 Rust toolchain
      uses: dtolnay/rust-toolchain@1.79

    - name: Install cargo-hack
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-hack

    # Oops, I changed the API of the xtask package after commit `3705cd0`...
    #
    # FIXME: `xtask ci` may run `cargo build`, overwriting its own binary.
    # FIXME: This is not possible on Windows, so install it before running it.
    - name: Check old commits on ${{ matrix.branch }} (Rust 1.79)
      run: >
        git checkout 3705cd01e514bb3252eba6f4f69ec61168e141a3

        git rebase
        --root
        --exec 'cargo install --path xtask'
        --exec 'xtask ci --skip-moving-targets'

        git checkout 57cc064646a878328324122dc7c00fd44fd2cc35

        git rebase
        3705cd01e514bb3252eba6f4f69ec61168e141a3
        --exec 'cargo install --path xtask'
        --exec 'xtask ci all --skip-moving-targets'

    - name: Install stable Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Check remaining commits on ${{ matrix.branch }} (stable Rust)
      run: >
        git checkout ${{ github.sha }}

        git rebase
        57cc064646a878328324122dc7c00fd44fd2cc35
        --exec 'cargo install --path xtask'
        --exec 'xtask ci all --skip-moving-targets'
