# Checks if all past commits pass the CI quality gate `cargo xtask ci`,
# excluding moving targets (such as clippy or `cargo audit`).
# This pipeline tries to indicate whether developers may use `git bisect`.

name: Validate entire commit history

on:
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │ ┌───────────── hour (0 - 23)
    #        │ │ ┌───────────── day of the month (1 - 31)
    #        │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │ │ │ │ │
    #        │ │ │ │ │
    #        │ │ │ │ │
    - cron: '0 0 * * MON'

jobs:
  check_each_commit:
    name: check each commit
    timeout-minutes: 15
    runs-on: ${{ matrix.system }}

    strategy:
      matrix:
        system: [ ubuntu-latest, windows-latest, macos-latest ]
        branch: [ dev/0.1, pub/0.1 ]

    steps:

    - uses: actions/checkout@v4
      with:
        ref: ${{ matrix.branch }}

    - name: Install stable Rust toolchain with clippy
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy

    - name: Install nightly Rust toolchain with rustfmt and miri
      uses: dtolnay/rust-toolchain@nightly
      with:
        components: rustfmt, miri

    - name: Install cargo-hack
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-hack

    # Run `cargo update` because `xtask` would fail if `Cargo.lock` is outdated.
    # `Cargo.lock` of library crates is not published / used by other people.
    # TODO: In binary projects, do NOT update/restore `Cargo.lock`.
    - name: Check each commit on ${{ matrix.branch }}
      run: >
        git rebase
        --root
        --exec 'cargo update'
        --exec 'cargo xtask ci all --skip-moving-targets'
        --exec 'git checkout Cargo.lock'
