# Runs the CI quality gate: compilation, linting, testing, dependency checking,
# and so on, on every single commit that would be added by the pull request,
# each time the pull request receives a new push or is (re-)opened.
#
# Does not validate the result of the actual merge.
# See `validate_git_head.yaml` for that.
#
# Please note the following refs:
#
# - github.ref      → refs/pull/$id/merge
# - github.head_ref → $source_branch_name, e.g. "feature/foobar"
# - github.base_ref → $destination_branch, e.g. "dev/0.1" or "main"

name: Validate PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches-ignore:
      - 'pub/*'

jobs:
  check_each_commit:
    name: check each commit
    timeout-minutes: 60
    runs-on: ${{ matrix.system }}

    strategy:
      matrix:
        system: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:

    # Avoid linter errors due to changed line endings
    - run: git config --global core.autocrlf false

    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Fetch commits on ${{ github.head_ref }} reachable from ${{ github.base_ref }}
      # Note that the command below fetches too much data.
      # Feel free to adjust the command according to the
      # requirement above. In May 2020, trying to be precise
      # seemed to trigger a deadlock in Git or GitHub here.
      run: git fetch --no-tags --prune --unshallow origin

    - name: Install nightly Rust toolchain with rustfmt and miri
      uses: dtolnay/rust-toolchain@nightly
      with:
        components: rustfmt, miri

    - name: Setup MIRI
      run: cargo +nightly miri setup

    - name: Install stable Rust toolchain with clippy
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy

    - name: Install cargo-hack
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-hack

    - name: Install cargo-tarpaulin
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-tarpaulin

    - name: Install cargo-upgrades
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-upgrades

    - name: Install cargo-audit
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-audit

    # Run checks without MIRI first to avoid `cargo clean` between rebase steps.
    # Run `cargo update` because `xtask` would fail if `Cargo.lock` is outdated.
    # `Cargo.lock` of library crates is not published / used by other people.
    # TODO: In binary projects, do NOT update/restore `Cargo.lock`.
    - name: Check each commit added by this PR (w/o MIRI)
      run: >
        git rebase
        --fork-point origin/${{ github.base_ref }}
        --exec 'cargo update'
        --exec 'cargo xtask ci all --skip-miri'
        --exec 'git checkout Cargo.lock'

    # Run checks without MIRI first to avoid `cargo clean` between rebase steps.
    # Run `cargo update` because `xtask` would fail if `Cargo.lock` is outdated.
    # `Cargo.lock` of library crates is not published / used by other people.
    # TODO: In binary projects, do NOT update/restore `Cargo.lock`.
    # FIXME: `xtask ci miri` run `cargo clean`, deleting its own binary.
    # FIXME: This is not possible on Windows, so install it before running it.
    - name: Check each commit added by this PR (MIRI only)
      run: >
        git rebase
        --fork-point origin/${{ github.base_ref }}
        --exec 'cargo update'
        --exec 'cargo install --path xtask'
        --exec 'xtask ci miri'
        --exec 'git checkout Cargo.lock'
