# Runs `cargo xtask ci` (implemented in the `xtask` crate)
# on what would be the result of merging a pull request, as well as
# on every single commit that would be added by the pull request,
# each time the pull request receives a new push or is (re-)opened.
#
# Does not validate the result of the actual merge.
# See `validate_git_head.yaml` for that.
#
# Please note the following refs:
#
# - github.ref      → refs/pull/$id/merge
# - github.head_ref → $source_branch_name, e.g. "feature/foobar"
# - github.base_ref → $destination_branch, e.g. "dev/0.1" or "main"

name: Validate PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - '**'

jobs:
  check_each_commit:
    name: check each commit
    timeout-minutes: 15
    runs-on: ${{ matrix.system }}

    strategy:
      matrix:
        system: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:

    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Fetch commits on ${{ github.head_ref }} reachable from ${{ github.base_ref }}
      # Note that the command below fetches too much data.
      # Feel free to adjust the command according to the
      # requirement above. In May 2020, trying to be precise
      # seemed to trigger a deadlock in Git or GitHub here.
      run: git fetch --no-tags --prune --unshallow origin

    - name: Install stable Rust toolchain with clippy
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy

    - name: Install nightly Rust toolchain with rustfmt and miri
      uses: dtolnay/rust-toolchain@nightly
      with:
        components: rustfmt, miri

    - name: Install cargo-hack
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-hack

    - name: Check each commit added by this PR
      run: >
        git rebase
        --fork-point origin/${{ github.base_ref }}
        --exec 'cargo xtask ci'
